stages:
  - build
  - deploy

variables:
  CI_REGISTRY: gitlab.flextech.asia:5050
  #  IMAGE_TAG: $CI_REGISTRY/e-learning/os-live-class:$CI_COMMIT_REF_NAME
  IMAGE_TAG_API: $CI_REGISTRY/lms-university/liveclass-api/api
  IMAGE_TAG_SOCKET: $CI_REGISTRY/lms-university/liveclass-api/socket

Build API:
  stage: build
  script:
    - echo $IMAGE_TAG_API-$CI_COMMIT_SHORT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build -t $IMAGE_TAG_API -t $IMAGE_TAG_API:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_TAG_API:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_TAG_API
  only:
    - develop

Build Socket:
  stage: build
  script:
    - echo $IMAGE_TAG_SOCKET-$CI_COMMIT_SHORT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build -t $IMAGE_TAG_SOCKET -t $IMAGE_TAG_SOCKET:$CI_COMMIT_SHORT_SHA -f apps/receiver/Dockerfile .
    - docker push $IMAGE_TAG_SOCKET:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_TAG_SOCKET
  only:
    - socket

Deploy Develop:
  stage: deploy
  script:
    - echo image_tag $IMAGE_TAG_API ci_commit $CI_COMMIT_SHORT_SHA
    - curl -XPOST $WWW_WEBHOOK
  environment:
    name: develop
  only:
    - develop

Deploy Socket:
  stage: deploy
  script:
    - echo image_tag $IMAGE_TAG_SOCKET ci_commit $CI_COMMIT_SHORT_SHA
    - curl -XPOST $WWW_WEBHOOK
  environment:
    name: socket
  only:
    - socket
